#!/usr/bin/env bash
#
# One command. Run it, then go and listen to the talk — the installs take
# about a minute and you want them finished before the room starts building.
#
#   ./setup.sh
#
set -euo pipefail
cd "$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '  \033[31m✗\033[0m %s\n\n' "$*" >&2; exit 1; }

say "checking your toolchain"

command -v node >/dev/null || die "node is not installed. You need Node 20.6 or newer."
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
NODE_MINOR=$(node -p 'process.versions.node.split(".")[1]')
if [ "$NODE_MAJOR" -lt 20 ] || { [ "$NODE_MAJOR" -eq 20 ] && [ "$NODE_MINOR" -lt 6 ]; }; then
  die "node $(node -v) is too old. You need 20.6 or newer (we use process.loadEnvFile)."
fi
ok "node $(node -v)"

command -v npm >/dev/null || die "npm is not installed."
ok "npm $(npm -v)"

# Each run gets its own throwaway git repo so your agent can diff its own work.
command -v git >/dev/null || die "git is not installed."
ok "git $(git --version | awk '{print $3}')"

say "installing the harness"
npm install --silent
ok "harness dependencies"

say "installing the problem repo"
if [ ! -d problems/minicalc ]; then
  die "problems/minicalc is missing. Re-clone — this repo is incomplete."
fi
(cd problems/minicalc && npm install --silent)
ok "minicalc dependencies"

say "credentials"
if [ ! -f .env ]; then
  cp .env.example .env
  warn "created .env from the example — it has no key in it yet"
else
  ok ".env exists"
fi

HAS_KEY=0
grep -qE '^(OPENAI_API_KEY|AZURE_OPENAI_API_KEY)=.+' .env 2>/dev/null && HAS_KEY=1
if [ "$HAS_KEY" -eq 0 ]; then
  warn "no API key in .env yet — put one in before you run anything"
fi

say "building the CLI entry point"
cat > jam <<'LAUNCHER'
#!/usr/bin/env bash
# Generated by setup.sh. Resolves through the symlink `npm link` creates so
# `jam` works from any directory.
SELF="${BASH_SOURCE[0]}"
while [ -L "$SELF" ]; do
  DIR="$(cd -P "$(dirname "$SELF")" && pwd)"
  SELF="$(readlink "$SELF")"
  [[ $SELF != /* ]] && SELF="$DIR/$SELF"
done
ROOT="$(cd -P "$(dirname "$SELF")" && pwd)"

# Call the local binary directly. `npx --prefix` would export npm_config_prefix,
# which breaks nvm in every child process the harness spawns.
TSX="$ROOT/node_modules/.bin/tsx"
if [ ! -x "$TSX" ]; then
  echo "dependencies are missing - run ./setup.sh" >&2
  exit 1
fi
exec "$TSX" "$ROOT/cli/index.ts" "$@"
LAUNCHER
chmod +x jam
ok "./jam"

say "linking the CLI"
if npm link >/dev/null 2>&1; then
  ok "\`jam\` is on your PATH"
else
  warn "could not link globally — use ./jam instead, it works identically"
fi

say "checking the problem"
FAILING=$(cd problems/minicalc && npx vitest run --reporter=json --outputFile=/tmp/jam-setup.json >/dev/null 2>&1 || true; \
  node -e '
    const r = require("/tmp/jam-setup.json");
    const all = r.testResults.flatMap(t => t.assertionResults);
    console.log(all.filter(a => a.status !== "passed").length + "/" + all.length);
  ')
ok "$FAILING tests failing — that is the job"

say "you are set up"
cat <<'NEXT'
  Read harness/main.ts. That is the harness, and it is yours.

    jam run --n 1 -w        one task, streaming, about a minute
    jam run                 everything
    jam show                what happened

  If `jam` is not found, use ./jam.

NEXT
if [ "$HAS_KEY" -eq 0 ]; then
  printf '  \033[33mPut an API key in .env first — nothing will run without one.\033[0m\n\n'
fi
